@echo off
REM ============================================================
REM Publish a release that existing installs can auto-update to.
REM Prereq: build-exe.cmd tauri <ver> has been run (dist\ populated).
REM
REM   scripts\publish.cmd <ver> [notes]
REM   e.g. scripts\publish.cmd 3.4.0 "fix a, add b"
REM
REM Steps:
REM   1. sanity-check dist\latest.json (generated by scripts\make-latest.js)
REM      and the signed installer + .sig
REM   2. git tag v<ver> and push it
REM   3. gh release create, uploading installer + .sig + latest.json
REM      Asset names are fixed by convention; the app's updater endpoint is
REM      releases/latest/download/latest.json which always resolves to the
REM      newest release.
REM Prereq: gh CLI logged in (gh auth login). Without gh, manual steps are
REM printed instead.
REM NOTE: keep this file ASCII-only (cmd parses it with the ANSI codepage).
REM ============================================================
setlocal enabledelayedexpansion
cd /d %~dp0..

set "VER=%~1"
if "%VER%"=="" (
  echo Usage: scripts\publish.cmd ^<ver^> [notes]
  echo e.g.   scripts\publish.cmd 3.4.0 "fix a, add b"
  exit /b 1
)

set "EXE=x-code_%VER%_x64-setup.exe"
set "LATEST=dist\latest.json"

if not exist "%LATEST%" (
  echo [publish] %LATEST% missing - run first: build-exe.cmd tauri %VER% ^&^& node scripts\make-latest.js
  exit /b 1
)
findstr /c:"\"version\": \"%VER%\"" "%LATEST%" >nul
if errorlevel 1 (
  echo [publish] Version mismatch in %LATEST% vs %VER% - re-run: node scripts\make-latest.js
  exit /b 1
)
if not exist "dist\%EXE%" (
  echo [publish] Missing dist\%EXE%
  exit /b 1
)
if not exist "dist\%EXE%.sig" (
  echo [publish] Missing dist\%EXE%.sig - releases MUST ship the signature, or existing installs cannot auto-update to this version
  exit /b 1
)

echo [publish] Pushing tag v%VER% ...
git tag -f v%VER%
git push origin v%VER%
if errorlevel 1 exit /b 1

where gh >nul 2>&1
if errorlevel 1 goto :manual
gh auth status >nul 2>&1
if errorlevel 1 (
  echo [publish] gh is not logged in. Run: gh auth login
  echo [publish] Or set the GH_TOKEN environment variable, then re-run this script.
  goto :manual
)

set "NOTES=%~2"
if "%NOTES%"=="" set "NOTES=x-code v%VER%"

echo [publish] Creating GitHub release v%VER% and uploading assets ...
gh release create v%VER% "dist\%EXE%" "dist\%EXE%.sig" "%LATEST%" --title "x-code v%VER%" --notes "%NOTES%"
if errorlevel 1 (
  echo [publish] gh failed - the release may already exist. Try:
  echo [publish]   gh release upload v%VER% dist\%EXE% dist\%EXE%.sig dist\latest.json --clobber
  exit /b 1
)
echo [publish] Done. Users on older versions will get the update on next app start.
goto :eof

:manual
echo [publish] gh CLI not found. Publish manually:
echo   1. Open https://github.com/Steve-pixel-cpu/x-code/releases/new?tag=v%VER%
echo   2. Upload all three files: dist\%EXE%  dist\%EXE%.sig  dist\latest.json
echo   3. Title it "x-code v%VER%" and publish
exit /b 1
